#!/bin/sh

userresources="${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources"
usermodmap="${XDG_CONFIG_HOME:-$HOME/.config}/.Xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	[ -x "$f" ] && . "$f"
 done
 unset f
fi

USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
        . "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
else
        . "$HOME/.xprofile"
fi

[[ "$WM" ]] && exec "$WM" || echo "No window manager is set: use 'export VM=window-manager'."
