#!/bin/dash


screens 																# set screens configuration
xautolock -time 30 -locker "$LOCKER" &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &

pgrep xfce4-power-manager \
	|| xfce4-power-manager --daemon &			# power manager
pgrep nm-applet \
	|| nm-applet --indicator &						# network applet
pgrep picom || picom &                  # compositor for opacity
pgrep dunst || dunst &                  # notification-daemons
pgrep mullvad-vpn || mullvad-vpn &      # vpn connection
pgrep redshift-gtk || redshift-gtk &    # colour temperate adjustment
pgrep unclutter || unclutter &          # hides mouse cursor when idle
wallp restore &                         # set wallpaper
clipmenud &                             # clipmenu daemon
remapkeys &                             # set capslock as control/escape
pgrep emacs || emacs --daemon &					# emacs server
protonmail-bridge &
