#!/bin/sh

#
# wm independent hotkeys
#

# make sxhkd reload its configuration files:
super + Escape
  pkill -USR1 -x sxhkd; notify-send 'sxhkd' 'Reload configuration.'

# terminal emulator
super + Return
	$TERMINAL

# program launchers
super + {r,p}
  {$LAUNCHER, $LAUNCHER_ALT}

# custom quick launch
super + shift + Return
  quicklaunch

# window explorer
super + Tab
	rofi -show window

# slock
ctrl + alt + l
	slock

super + o ; {e,c,w,b,m}
	{emacs,org-capture,quicklaunch-websearch,quicklaunch-bookmarks,thunderbird}

#
# System keys
#

XF86MonBrightness{Up,Down}
	xbacklight -{inc,dec} 5
XF86Audio{Raise,Lower}Volume
	pactl -- set-sink-volume 0 {+,-}5% > /dev/null
XF86AudioMute
	pactl -- set-sink-mute 0 toggle > /dev/null
XF86AudioPlay
	mpc toggle
XF86AudioNext
	mpc next
XF86AudioPrev
	mpc prev
