#!/bin/sh

#
# wm independent hotkeys
#

# make sxhkd reload its configuration files:
super + ctrl + Escape
  pkill -USR1 -x sxhkd; notify-send 'sxhkd' 'Reload configuration.'

# terminal emulator
super + Return
	$TERMINAL

# program launchers
super + {r, shift + r}
  {$LAUNCHER, $LAUNCHER_ALT}

# custom quick launch
super + shift + Return
  quicklaunch

# window explorer
super + Tab
	launcher_windows

# slock
ctrl + alt + l
	slock

super + o ; {e,c,f,w,b,m}
	{emacs,org-capture,thunar,quicklaunch-websearch,quicklaunch-bookmarks,thunderbird}

alt + m
	amixer -D pulse sset Capture toggle

#
# System keys
#

XF86MonBrightness{Up,Down}
	xbacklight -{inc,dec} 5
XF86Audio{Raise,Lower}Volume
	pactl -- set-sink-volume 0 {+,-}5% > /dev/null
XF86AudioMute
	pactl -- set-sink-mute 0 toggle > /dev/null
XF86AudioPlay
	mpc toggle
XF86AudioNext
	mpc next
XF86AudioPrev
	mpc prev
