#!/bin/dash

# To temporarily bypass an alias, we preceed the command with a \
# EG:  the ls command is aliased,
# but to use the normal ls command you would type \ls

# Verbosity
alias ls="ls -hNA --color=auto --group-directories-first"
alias ll="ls -lhFA --color=auto --group-directories-first"
alias cd=cdls
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkdir="mkdir -pv"

cdls() { builtin cd $@ && ls; }

# frequent use programs
alias p="sudo pacman"
alias vim=nvim
alias v=vim
alias top=htop
alias diff=colordiff
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
alias mpv="setsid -f mpv"

# dotfiles
alias dotfiles="/usr/bin/git --git-dir=$HOME/Projects/dotfiles --work-tree=$HOME"
alias dof="dotfiles"
alias dofa="dotfiles add"
alias dofs="dotfiles status"
alias dofc="dof commit"
alias dofl="dof log"
alias dofd="dof diff"
alias dofds="dof diff --staged"

# git
alias g="git"
alias gs="git status"
alias ga="git add"
alias gpl="git pull"
alias gps="git push"
alias gc="git commit"
alias gl="git log"
alias gd="git diff"
alias gds="git diff --staged"

# Search and...
alias s="fuzzysearch"
alias si="fuzzysearch --inside"

search_and() { s ~/.config/ ~/.local/scripts/ ~/.w3m "${@:2}" | xargs -r -I % sh -c "$1 %"; }
se() { search_and "$EDITOR" "${1}"; }
sc() { search_and "$PAGER" "${1}"; }

search_inside_and() { si ~/.config/ ~/.local/scripts/ ~/.w3m "${@:2}" | cut -d':' -f1 | xargs -r -I % sh -c "$1 %"; }
sie() { search_inside_and "$EDITOR" "${1}"; }
sic() { search_inside_and "$PAGER" "${1}"; }

# youtube-dl
alias ytdl="youtube-dl"
alias ytdla="youtube-dl -x -format bestaudio[ext=m4a] --embed-thumbnail"

play-yt() { setsid -f mpv ytdl://ytsearch:"$*"; }
play-yt-audio() { mpv --ytdl-format=bestaudio ytdl://ytsearch:"$*"; }

# working environments
alias notebook="~/Projects/resources/notebook/notebook.sh"
alias exercism="~/Projects/exercism/exercism.sh"

# toolboxes comands
#alias mix="toolbox --container elixir run mix"

# other stuff
alias nvidia-smi="watch -n 1 nvidia-smi"
alias nvidia-settings="nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings"
