#!/bin/dash

# To temporarily bypass an alias, we preceed the command with a \
# EG:  the ls command is aliased,
# but to use the normal ls command you would type \ls

# Verbosity
alias ls="ls -hNA --color=auto --group-directories-first"
alias ll="ls -lhFA --color=auto --group-directories-first"
alias cd=cdls
alias cp="cp -iv"
alias grep="grep --color=auto"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkdir="mkdir -pv"

cdls() { builtin cd $@ && ls; }
mkcd() { mkdir $@ && cdls $@ && pwd; }

# frequent use programs
alias diff=delta
#alias mpv="devour mpv"
alias p="sudo pacman"
alias pidgin="pidgin --config=${XDG_DATA_HOME:-$HOME/.local/share}/purple"
alias top=htop
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
alias vim=nvim
alias v=vim

# doom emacs
alias doom="$HOME/.local/src/doom-emacs/bin/doom --localdir=${XDG_DATA_HOME:-$HOME/.local/share}/doom"

# dotfiles
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/.git --work-tree=$HOME/.dotfiles/"
alias dof="dotfiles"
alias dofs="dotfiles status"

# git
alias g="git"
alias gs="git status"
alias ga="git add"
alias gpll="git pull"
alias gpsh="git push"
alias gc="git commit"
alias gl="git log --oneline -n 20"
alias gd="git diff"
alias gds="git diff --staged"
alias gr="git restore"
alias grs="git restore --staged"
alias gb="git branch"
alias gba="git branch -a"

# Search and...
alias s="fuzzysearch"
alias si="fuzzysearch --inside"

search_and() { s ~/.config/ ~/.local/scripts/ ~/.w3m "${@:2}" | xargs -r -I % sh -c "$1 %"; }
se() { search_and "$EDITOR" "${1}"; }
sc() { search_and "$PAGER" "${1}"; }

search_inside_and() { si ~/.config/ ~/.local/scripts/ ~/.w3m "${@:2}" | cut -d':' -f1 | xargs -r -I % sh -c "$1 %"; }
sie() { search_inside_and "$EDITOR" "${1}"; }
sic() { search_inside_and "$PAGER" "${1}"; }

# youtube-dl
alias ytdl="youtube-dl"
alias ytdla="youtube-dl -x -format bestaudio[ext=m4a] --embed-thumbnail"
alias ytdla-playlist="youtube-dl -x --audio-format mp3 -o '%(playlist)s/%(playlist_index)s.%(title)s.%(ext)s'"

play-yt() { \mpv --ytdl-format="bestvideo[ext=mp4][height<=480]+bestaudio" ytdl://ytsearch:"$*"; }
play-yt-audio() { \mpv --ytdl-format=bestaudio ytdl://ytsearch:"$*"; }

# working environments
alias notebook="~/Projects/resources/notebook/notebook.sh"
alias exercism="~/Projects/exercism/exercism.sh"

# toolboxes comands
#alias mix="toolbox --container elixir run mix"

# other stuff
alias nvidia-smi="watch -n 1 nvidia-smi"
alias nvidia-settings="nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings"
