#!/bin/sh

pgrep bspswallow || bspswallow &
pgrep bspcleanfullscreen || bspcleanfullscreen &
"$XDG_CONFIG_HOME"/polybar/launch.sh

displays=$(xrandr | awk '/ connected/ {print $0}')
primary=$(echo "$displays" | grep "primary" | awk -F '[[:space:]]+' '{print $1}')
secondary=$(echo "$displays" | grep -v "primary" | awk -F '[[:space:]]+' '{print $1}' | head -1)

if [ "$(echo "$displays" | wc -l)" -gt 1 ]; then
	bspc monitor "$primary"		-d 1 2 3 4 5
	bspc monitor "$secondary" -d 6 7 8 9 10
else
	bspc monitor "$primary"		-d 1 2 3 4 5 6 7 8 9 10
fi

bspc config automatic_scheme		alternate

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding					30

bspc config split_ratio					0.52
bspc config borderless_monocle	true
bspc config gapless_monocle			true

bspc config remove_disabled_monitors		true
bspc config remove_unplugged_monitors		true

bspc rule -a scratchpad sticky=on state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Emacs:*:capture sticky=on state=floating

bspc rule -a Slack desktop='^9'
bspc rule -a Signal desktop='^9'
bspc rule -a firefox desktop='^6'
bspc rule -a Firefox desktop='^6'
bspc rule -a "Tor Browser" desktop='^6'
bspc rule -a Lutris desktop='^5'
bspc rule -a Steam desktop='^5'
bspc rule -a Virt-manager desktop='^7'
bspc rule -a "ProtonMail Bridge" desktop='^8'
bspc rule -a Thunderbird desktop='^8'

# pywal
# source the colors.
. "${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
