#! /bin/sh

pgrep picom || /usr/bin/picom &
pgrep redshift || /usr/bin/redshift &
pgrep dunst || /usr/bin/dunst &
pgrep mullvad || /usr/bin/mullvad connect &

$XDG_CONFIG_HOME/fehbg &
$XDG_CONFIG_HOME/polybar/launch.sh
$XDG_CONFIG_HOME/sxhkd/launch.sh


bspc monitor eDP1 -d I II III IV V
bspc monitor DP3 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8
bspc config top_padding 				30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
