#! /bin/sh

$XDG_CONFIG_HOME/polybar/launch.sh
$XDG_CONFIG_HOME/sxhkd/launch.sh

bspc monitor eDP1 -d I II III IV V
bspc monitor DP3 -d VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           8
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a scratchpad sticky=on state=floating
bspc rule -a firefox desktop='^6'
bspc rule -a "Tor Browser" desktop='^6'
bspc rule -a Emacs state=tiled

# pywal
# source the colors.
. "${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
