#!/bin/dash
# elvis: wordreference	-- Search wordreference.com

. surfraw || exit 1

w3_config
w3_parse_args "$@"

base_url="https://www.wordreference.com"

if [ -z "$w3_args" ]; then
    w3_browse_url "$base_url"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "$base_url/enfr/$escaped_args"
fi
